### ISSUE TITLE
[Feature request] Create template classification for prompts

### ISSUE THREAD

**Issue by rk-teche** [promptslab/PromptifyJs#2]
We have successfully created a classification for **Named Entity Recognition** (NER). There are other classifications which needs to be created using a similar approach, I would recommend following the steps outlined in the provided references. 

Classification List -

- [X] Named Entity Recognition
- [x] #3
- [x] #4
- [x] #5
- [x] #6

**Ref** : 

#1 - [Promptify Classification Reference](https://github.com/promptslab/Promptify/tree/main/promptify/prompts/nlp/templates)
#2 - [NER Classification Implementation](https://github.com/promptslab/PromptifyJs/blob/f9176cb7b703995470f4095233bf6660f8839093/config/ner.js#LL1)

**Comment by eren23** [comment]
Hey @rk-teche what features are still left open from this page, I can take a look at some of them, or as I did in the original promptify repo I can try to add different features etc. Just let me know so I can create a ticket already.
Thanks a lot for the great work BTW, the code is really easy to follow

**Comment by rk-teche** [comment]
We need to integrate [openai](https://www.npmjs.com/package/openai) and [huggingface](https://www.npmjs.com/package/huggingface-api) models. kindly refer to issue #9 for implementation.

**Comment by rk-teche** [comment]
Tabular & SQL data classification added

**Comment by robinzixuan** [comment]
What the task left now @rk-teche

**Comment by rk-teche** [comment]
Completed all the classification
