### ISSUE TITLE
Migrating Example Data From the Python Version

### ISSUE THREAD

**Issue by eren23** [promptslab/PromptifyJs#8]
I can open a PR for migrating the data from the original repo, or are there any other plans there? 

https://github.com/promptslab/Promptify/tree/main/examples/data

**Comment by rk-teche** [comment]
@eren23 Certainly, you can proceed with example data migration.

**Comment by eren23** [comment]
> @eren23 Certainly, you can proceed with example data migration.

I opened a PR for that #10 when I have more more time available I can also start migrating some examples directly.
